version: "3"
services:
  metabase-app:
    image: metabase/metabase
    restart: always
    container_name: metabase
    ports:
      - 3000:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data
networks:
  default:
      name: modern-data-stack